### PR TITLE
Password

### PR DESCRIPTION
**Pull request by Aravindha1234u**
Resolves Issue #15 

### Description
Added password.html inside Development/15-Password_Validation as menitoned. I haven't worked on any css part but html and javascript is perfectly working and I have attached the screenshot

### Screenshots (if required)
image
image

### How to run
Open html file in browser to test it out

### Checklist
- [X] Code compiles correctly.
- [X] Changes are tested properly.
- [X] Added the README / documentation, if necessary.
- [X] Followed the Contributing guidelines.
- [X] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by Aravindha1234u** [comment]
@gaurang2001 Can you check this pull request. Sorry Last one got messy because of contribution to Two Issues

**Comment by gaurang2001** [comment]
Hi @Aravindha1234u, 
The issue explicitly says that you have to claim it before making a related PR. Hence, I've assigned the issue to someone else who claimed the issue. You can still comment on the issue and you might get a chance work on it provided the current assignee fails to submit a PR within the given time of 3 days. Until then, feel free to explore other projects within the repo.

**Comment by Aravindha1234u** [comment]
Okk Sorry for that, If the assigned person fails to submit the work. Do consider me as next person @gaurang2001

**Comment by gaurang2001** [comment]
Please comment on the issue. Others who might be interested need to know that you are next in order.

**Comment by gaurang2001** [comment]
@Aravindha1234u The issue was to validate the password as and when the user types and not on form submission. Please change your code accordingly. Also, please specify what you mean by a strong password and a weak password.

**Comment by Aravindha1234u** [comment]
@gaurang2001 but check the issue last line it refers to registration and also mentions on success it should redirect to another page. So I guess this form submission is what you are referring to.

**Comment by gaurang2001** [comment]
>  Make a simple sign-up page that dynamically checks if the password entered is a strong password as and when the user types in the password field.

@Aravindha1234u This has clearly been specified in the issue. Nowhere have I mentioned validation on form submission.

**Comment by Aravindha1234u** [comment]
Okk, I will change accordingly.

**Pull request merged**
