### PR TITLE
REST API

### PR DESCRIPTION
**Pull request by mohitshende**
Resolves Issue #35 

### Description
Created a REST API using Express and NodeJS.

### How to run
1. To install node modules , open terminal in project folder and run the command ```npm install```

2. Now you can run the command ```npm start``` and the server will be up and running.

3. Then you can send all four HTTPS requests using tools like Postman.

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by viveshy** [comment]
@mohitshende Could you please specify the steps to run your submission? I'll review it and merge it there on.

**Comment by mohitshende** [comment]
First you have to install node modules. To do that open terminal in project folder and then type npm install , it'll install all dependencies of the project. Now you can type npm start to start the server. But as this is just API and doesn't have a frontend so you will have to use postman to send all four HTTPS requests.

**Comment by viveshy** [comment]
> First you have to install node modules. To do that open terminal in project folder and then type npm install , it'll install all dependencies of the project. Now you can type npm start to start the server. But as this is just API and doesn't have a frontend so you will have to use postman to send all four HTTPS requests.

@mohitshende Your code looks good. I need you to mention the installation guide in the PR template, i.e, "How to run section".

**Comment by mohitshende** [comment]
> @mohitshende Your code looks good. I need you to mention the installation guide in the PR template, i.e, "How to run section".

@viveshCodes , I have updated the PR  with installation steps. Now please check.

**Pull request merged**
