### PR TITLE
Added Python notebook and python file of Linear Regression on Boston …

### PR DESCRIPTION
**Pull request by Hemant7499**
…Housing Dataset- Hacktoberfest 2020

Resolves Issue #28 

### Description
Performed linear regression on the Housing dataset:
1)Checking distribution and colinearity of variables.
2)Scaling data
3) Principal Component Analysis for removing colinearity
4)Applying Linear Regression
5)Printing Root mean squared error nad R2 score.

### Technical Specifications
Python, Pandas, Numpy, Sklearn, Seaborn.

### How to run
Please list all the steps required to run in details. Preferably specify steps for all platforms.
1)Open the python notebook in desired editor for e.g. Google Colab, Jupyter Notebook, etc.
2)Run all the cells.

### CODE REVIEW

**Comment by Hemant7499** [comment]
@rakki-18 please review

**Comment by rakki-18** [comment]
@Smally12345 the code looks fine. But the directory structure is wrong. Make a folder "28_Housing_Price" under "MachineLearning" if it doesn't exist yet and not "28_Housing_Price/linearRegression".
Inside "28_Housing_Price", make a folder named "linearRegression" and inside that put all your files.
Please send another PR resolving this.

**Comment by Hemant7499** [comment]
image
I have created linearRegression folder inside 28_Housing_Price folder but  as you can see in the screenshot attached github skips paths for easy access.

**Comment by rakki-18** [comment]
@Smally12345 Everything is fine. Good work!

**Pull request merged**
