### PR TITLE
Longestprefix

### PR DESCRIPTION
**Pull request by SuyashGupte**
Resolves Issue #24 

### Description
Will ouput strings with the given prefix

### Technical Specifications
Uses rabin karp and poly hash function.

### How to run
Please list all the steps required to run in details. Preferably specify steps for all platforms.
python prg_name.py

### Checklist
- [X] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by krithikvaidya** [comment]
@spectre900 take a look

**Comment by spectre900** [comment]
@SuyashGupte 
your code should return the count of the words with the given prefix. 
Also it should work for multiple Prefix input and not just one.
Make necessary changes at the earliest.

**Comment by krithikvaidya** [comment]
@SuyashGupte make the changes asap so that the PR can be merged.

**Comment by spectre900** [comment]
@krithikvaidya 
The code is fine ... It can be merged

**Pull request merged**
