### PR TITLE
GUI for BMI calculator with python

### PR DESCRIPTION
**Pull request by KushGrandhi**
#32 GUI for BMI calculator with python

### Description
this is a desktop application to calculate BMI built on python

### Technical Specifications
libraries required are - 1. PysimpleGUI 2. Tkinter

### How to run
download the required libraries and just run :)
### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by krithikvaidya** [comment]
@KushGrandhi Code looks good to me, just edit the PR description and fill in the format properly so that I can merge it.

**Comment by KushGrandhi** [comment]
@krithikvaidya  im sorry, i dont understand what is the proper format, could you tell me what exactly has to be done

**Comment by krithikvaidya** [comment]
image
The text under each section (Description, How to run, etc) in the PR description here is placeholder text, you're supposed to replace it with text relevant to your PR

**Comment by KushGrandhi** [comment]
@krithikvaidya I have updated the original PR description

**Pull request merged**
