### PR TITLE
Create Percolation.java

### PR DESCRIPTION
**Pull request by dipanshug124**
Issue #11 

### Description
Written Percolation code in Java

### Technical Specifications
Code is in Java
Imported Java libraries from edu.princeton.cs.algs4.

### How to run
```
javac Percolation. java
java Percolation
```
### Checklist
- [ ] Code compiles correctly.
- [ ] Changes are tested properly.
- [ ] Followed the Contributing guidelines.
- [ ] Resolved merge conflicts, if any.

@Shreya301 Please review this

### CODE REVIEW

**Comment by dipanshug124** [comment]
@Shreya301 Please review this

**Review by Shreya301 — CHANGES_REQUESTED** [review]
The code works well, just one modification: The input given would be p, the probability of a site being open and not the open sites explicitly.
p fraction of total sites would have to be opened arbitrarily.
Please change the code accordingly

**Comment by krithikvaidya** [comment]
@dipanshug124 please make the requested changes, and your code will be merged

**Comment by krithikvaidya** [comment]
> @dipanshug124 please make the requested changes, and your code will be merged

@dipanshug124 reminder

**Pull request merged**
