### PR TITLE
Added Affine Cipher Decryption

### PR DESCRIPTION
**Pull request by ritikgarg655**
Resolves Issue #39 

### Description
Added affine_cypher.cpp file in stated folder which will decrypt given string.

### Technical Specifications
Added function decrypt_cipher which return strings output.

### How to run
Compile by running command: "g++ affine_cypher.cpp"
Run using: "./a.out"
Than enter input as per displayed.

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by ritikgarg655** [comment]
@niranjansy please review PR.

**Review by niranjansy — COMMENTED** [review]
Good job! However, you can consider extending you code to work on both upper case and lower case letters.

**Comment by ritikgarg655** [comment]
@niranjansy Great suggestion. I will add it also.

**Comment by krithikvaidya** [comment]
@niranjansy should I go ahead and merge it?

**Comment by niranjansy** [comment]
@krithikvaidya Yes you can merge it.

**Pull request merged**
