### PR TITLE
Added RSA algorithm in JAVA

### PR DESCRIPTION
**Pull request by jarvis-1805**
Resolves Issue #63

### Description
Implementation of the RSA algorithm, that is used to encrypt a message without the need to exchange a secret key separately..

### Technical Specifications
Language: JAVA
OpenJDK Version: 11.0.2
OpenJDK RE: 18.9 (build 11.0.2+9)
Packages Used: 
```
java.util.Random
java.math.BigInteger
java.security.SecureRandom
```

### Screenshots (if required)
Output screenshot as ```output.jpg```.

### How to run
Linux OS and Windows OS
```
javac RSA.java
java RSA
```

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts if any.

### CODE REVIEW

**Comment by jarvis-1805** [comment]
Hey! @aksh555 please review it.

**Review by aksh555 — CHANGES_REQUESTED** [review]
@jarvis-1805 a small change, pls remove the java binary files

**Comment by jarvis-1805** [comment]
@aksh555 I've removed the binary files.

**Review by aksh555 — APPROVED** [review]
@jarvis-1805 good job! @krithikvaidya can merge this

**Comment by jarvis-1805** [comment]
Thanks! @aksh555 : )

**Pull request merged**
