### PR TITLE
 Dining Philosophers Problem

### PR DESCRIPTION
**Pull request by SPandeyCodes**
Resolves Issue #86 

### Description
  The dining philosophers problem states that there are 5 philosophers sharing a circular table and they eat and think alternatively. There is a bowl of rice for each of the philosophers and 5 chopsticks. A philosopher needs both their right and left chopstick to eat.
  The same problem is solved here using semaphores using C language. The eating process can be limited (or infinite) based on the user. 

### Technical Specifications
        Use C language to solve the Problem

### Screenshots (if required)
         Screenshots taken from an online compiler is attached along with the folder. 

### How to run
       use C compiler and can be a simple run without any input methods.

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [ ] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by SPandeyCodes** [comment]
Create Dining Philosophers Problem with semaphores using C

**Comment by SPandeyCodes** [comment]
Hi @suhasks123 . Please review.

**Comment by viveshy** [comment]
@suhasks123, is the PR good to be merged?

**Comment by viveshy** [comment]
@SPandeyCodes Add the screenshots of your working program and then it'll be merged. Add screenshots containing the following:
- Input
- Output

**Pull request merged**
