### PR TITLE
Maxstack

### PR DESCRIPTION
**Pull request by Pratap2018**
Resolves Issue #13 

### Description
Created Stack Class in Python With Max

### Technical Specifications
Push O(1) :Push Element To Top
Pop O(1) : POP Element From Top
get_maxO(n) : Returns max Element from the stack
Peek O(n): Returns Top Element
Size O(1) : Returns Size of the stack
### How to run
Please list all the steps required to run in details. Preferably specify steps for all platforms.

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added Multiline Comments in the code
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

@srujangit123 Please Review

### CODE REVIEW

**Comment by srujangit123** [comment]
@Pratap2018  Improve the efficiency of the operations. You can get the maximum element in O(1)

**Comment by Pratap2018** [comment]
Improved Efficiency of The operations of get_max O(N) to O(1)
@srujangit123

**Comment by srujangit123** [comment]
Pushed Element : 10
Max Element : 10
Pushed Element : 2
Max Element : 10
Pushed Element : 50
Max Element : 50
Pushed Element : 45
Max Element : 50
Pushed Element : 30
Max Element : 45

When you push 30, max element is still 50. But the output is 45.

**Comment by Pratap2018** [comment]
> Pushed Element : 10
> Max Element : 10
> Pushed Element : 2
> Max Element : 10
> Pushed Element : 50
> Max Element : 50
> Pushed Element : 45
> Max Element : 50
> Pushed Element : 30
> Max Element : 45
> 
> When you push 30, max element is still 50. But the output is 45.

I am sorry that happened , I have fixed it

**Comment by krithikvaidya** [comment]
@srujangit123 is the code fine to merge?

**Comment by Pratap2018** [comment]
yes you can run and check it .

**Comment by srujangit123** [comment]
Yes @krithikvaidya . You can merge

**Pull request merged**
