### PR TITLE
Added the web version of BMI calculator

### PR DESCRIPTION
**Pull request by sakkshm**
Resolves Issue #8 

**Description**
Created the web version (HTML CSS JS) for the BMI calculator.

**Technical Specifications**
Made using HTML , CSS and JS.

Screenshots (if required)
screenshot: https://i.ibb.co/FnB5h4L/Shared-Screenshot.jpg 

**How to run**
Open the file in a web browser

**Checklist**
 

- [x] Code compiles correctly.

- [x]  Changes are tested properly.

- [x] Followed the Contributing guidelines.

### CODE REVIEW

**Comment by krithikvaidya** [comment]
@sakkshm code looks good to me, just edit the PR description to follow the preset format and i'll merge it.

**Comment by sakkshm** [comment]
@krithikvaidya I have done the changes, kindly check it.

**Comment by krithikvaidya** [comment]
Nice, one last thing, rename the folder to *8_BMI* instead of *Web BMI Calculator*, like it was mentioned in the issue

**Comment by sakkshm** [comment]
@krithikvaidya Done!

**Pull request merged**
