### PR TITLE
Create SQL query

### PR DESCRIPTION
**Pull request by jainsarthak216**
Resolves Issue #<issue_number>

### Description
Please explain the changes you made in detail here.

### How to run
Please list all the steps required to run in details. Preferably specify steps for all platforms.

### Checklist
- [ ] Code compiles correctly.
- [ ] Changes are tested properly.
- [ ] Added the README / documentation, if necessary.
- [ ] Followed the Contributing guidelines.
- [ ] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by viveshy** [comment]
@jainsarthak216 Please add the details of your work in the pull request template. After editing it, mention your assignor to review the PR.

**Comment by jainsarthak216** [comment]
This PR was made for the issue SQL Operations using MySQL or SQLite3 #89.

**Comment by jainsarthak216** [comment]
This PR was made for the issue SQL Operations using MySQL or SQLite3 #89.

**Comment by krithikvaidya** [comment]
image
@jainsarthak216 Please replace the instructions in your PR description with details relevant to your PR.

**Pull request closed without merging**
