### PR TITLE
Solve String Transformation

### PR DESCRIPTION
**Pull request by SPandeyCodes**
Resolves Issue #<70>

### Description
 Find the least number of operations required to transform a given string into another given string.
The allowed operations are:

Add one character to the string.
Remove one character from the string.
Replace one character in the string.
For example, the minimum number of operations required for the strings "FALL" and "TALL" is 1, because you can replace F with T.

Calculate the least number of operations required for two given strings.

Input:
The first input line has a string of length n that contains characters between A–Z.
The second input line has a string of length m that contains characters between A–Z.

Output:
Print the minimum number of required operations.

Constraints: 1 ≤ n, m ≤5000

### Technical Specifications
 Used C++

### How to run
Run the c+ program.

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Followed the Contributing guidelines.

### CODE REVIEW

**Comment by SPandeyCodes** [comment]
@varun-raghavendra Please review.

**Comment by varun-raghavendra** [comment]
Please check your file again. Improve upon your answer. You have time till tomorrow 12 PM.

**Comment by krithikvaidya** [comment]
@varun-raghavendra tell me if it's okay to merge now

**Comment by varun-raghavendra** [comment]
It's still not okay. The issue is open again

**Pull request closed without merging**
